# Generated by Django 5.2 on 2025-06-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_pedido_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='asaas_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
