# Generated by Django 5.2 on 2025-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0006_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='Centro', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua',
            field=models.CharField(default='Centro', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
