# Generated by Django 5.2 on 2025-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0007_rename_data_pedido_criado_em_remove_pedido_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='S/N', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rua',
            field=models.CharField(default='Rua Desconhecida', max_length=255),
        ),
    ]
