# Generated by Django 5.2 on 2025-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_alter_pedido_bairro_alter_pedido_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
