# Generated by Django 5.2 on 2025-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada', 'Retirada no Local'), ('delivery', 'Tele Entrega')], default='retirada', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rua',
            field=models.CharField(max_length=255),
        ),
    ]
